http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov&salary=300&departmentId=2
###
http://localhost:8080/employee/add?firstName=Sergi&lastName=Razin&salary=200&departmentId=2
###
http://localhost:8080/employee/add?firstName=Dima&lastName=Baranov&salary=100&departmentId=2
###
http://localhost:8080/employee/add?firstName=1213&lastName=134444&salary=400&departmentId=2
###
http://localhost:8080/employee/add?firstName=F09$&lastName=1e.,44&salary=600&departmentId=2
###
http://localhost:8080/employee/add?firstName=&lastName=&salary=600&departmentId=2
###
http://localhost:8080/employee/add?firstName=maxim&lastName=medvedev&salary=100&departmentId=3
###
http://localhost:8080/employee/findAll
###
http://localhost:8080/employee/find
###
http://localhost:8080/employee/remove?firstName=Ivan&lastName=Ivanov&salary=300&departmentId=2
###
http://localhost:8080/departments/all
###
http://localhost:8080/departments/return-all?departmentId=2
###
http://localhost:8080/departments/max-salary?departmentId=2
###
http://localhost:8080/departments/min-salary?departmentId=2





